version: '3.7'
services:
  paco-backend:
    image: paco-backend
    container_name: paco-backend
    environment:
        - FLASK_APP=paco
        - FLASK_ENV=production
    ports:
        - 80:5000

  mariadb:
    image: mariadb
    container_name: paco-mariadb
    volumes:
      - /var/lib/mysql
      - /var/lib/mariadb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8991:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: paco-phpmyadmin
    ports:
      - 8992:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: 123456
    depends_on:
      - mariadb